# https://docs.streamlit.io/library/advanced-features/configuration#client

[server]
folderWatchBlacklist = []
fileWatcherType = "auto"
cookieSecret = "a-random-key-appears-here"
headless = false
runOnSave = true
port = 3333

[browser]
gatherUsageStats = false # 사용 통계 수집 x

[theme]
primaryColor="#F63366"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="sans serif"

[logger]
level = "info"
messageFormat = "%(asctime)s %(message)s"

[client]
caching = true
displayEnabled = true
showErrorDetails = true
toolbarMode = "auto"
showSidebarNavigation = false

[runner]
magicEnabled = true
installTracer = false
fixMatplotlib = true
fastReruns = true
enforceSerializableSessionState = false
enumCoercion = "nameOnly"
